"""
Generate the ACDC 70/10/20 patient-level split, stratified by diagnostic group.

The ACDC training set has 100 patients, 20 per diagnostic group, stored in blocks:
patient001-020 DCM, 021-040 HCM, 041-060 MINF, 061-080 NOR, 081-100 RV. From every
group, 14 patients go to training, 2 to validation and 4 to testing, chosen by a seeded
shuffle, so the split is reproducible. When --raw is given, the group of every patient is
read from its Info.cfg and checked against the block assignment.

    python scripts/make_acdc_split.py --out splits --seed 2026 [--raw ACDC/database/training]
"""
import argparse, glob, os, random

BLOCKS = {"DCM": range(1, 21), "HCM": range(21, 41), "MINF": range(41, 61),
          "NOR": range(61, 81), "RV": range(81, 101)}

ap = argparse.ArgumentParser()
ap.add_argument("--out", default="splits")
ap.add_argument("--seed", type=int, default=2026)
ap.add_argument("--raw", default=None, help="optional: verify groups against Info.cfg")
a = ap.parse_args()

groups = {g: [f"patient{i:03d}" for i in r] for g, r in BLOCKS.items()}
if a.raw:
    for g, pids in groups.items():
        for p in pids:
            cfg = os.path.join(a.raw, p, "Info.cfg")
            info = dict(l.split(":", 1) for l in open(cfg) if ":" in l)
            assert info["Group"].strip() == g, f"{p}: Info.cfg says {info['Group'].strip()}, expected {g}"
    print("diagnostic groups verified against Info.cfg")

rng = random.Random(a.seed)
split = {"train": [], "val": [], "test": []}
for g in sorted(groups):
    ids = list(groups[g]); rng.shuffle(ids)
    split["test"] += ids[:4]; split["val"] += ids[4:6]; split["train"] += ids[6:]
hdr = ("# ACDC patient-level split, 70 / 10 / 20, generated by scripts/make_acdc_split.py with seed "
       f"{a.seed},\n# stratified by diagnostic group (14 / 2 / 4 patients from each of the five groups).\n"
       "# If you use a different published split, replace these three files and state its source.\n")
os.makedirs(a.out, exist_ok=True)
for k, v in split.items():
    with open(os.path.join(a.out, f"acdc_{k}.txt"), "w") as f:
        f.write(hdr + "".join(p + "\n" for p in sorted(v)))
    print(f"acdc_{k}.txt: {len(v)} patients")
